### PR TITLE
add pattern that got NSNotFound

### PR DESCRIPTION
**Pull request by keito5656**
If get NSNofound, crash.
So I think need this pattern.

### CODE REVIEW

**Comment by mantas** [comment]
Thank you for your contribution!

Why would it return original string instead of nil if nothing was found?

**Comment by keito5656** [comment]
Thank you for your review!
Your comment is right. I fixed.

**Comment by mantas** [comment]
Looks good! Do you mind to squash it into a single commit? Or I can squash while merging :)

**Comment by keito5656** [comment]
thanks !
I squashed commit !

**Comment by mantas** [comment]
Thank you, merged!

**Pull request merged**
